baseURL = "file:///data/vishvastAloka/mImAMsA/"
languageCode = "en-us"
title = "मीमांसायां विश्वासटिप्पन्यः"
theme = "sanskrit-documentation-theme-hugo"
publishDir = "build_offline_android"
disablePathToLower = true

[params]
  githubEditMePathBase = "https://github.com/vishvAsa/mImAMsA/edit/content/"
  contactLink = "https://github.com/vishvAsa/mImAMsA/issues/new"
  build_img = "https://github.com/vishvAsa/mImAMsA/actions/workflows/build.yml/badge.svg"
  build_url = "https://github.com/vishvAsa/mImAMsA/actions/workflows/build.yml"
  env = "production"  
  # disqusShortcode = "vvasuki-site"

[outputs]
  home = ["HTML", "RSS", "JSON", "CSV"]
  section = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe = true


[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false

[markup.goldmark.parser.attribute]
block = true
title = true

[markup.highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = false
  hl_Lines = ''
  lineAnchors = ''
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  noClasses = true
  style = 'friendly'
  tabWidth = 2

