baseURL = "file:///storage/emulated/0/notesData/mImAMsA/"
languageCode = "en-us"
title = "संस्कारे विश्वासटिप्पन्यः"
theme = "sanskrit-documentation-theme-hugo"
publishDir = "build_offline_android"
disablePathToLower = true

[params]
  githubEditMePathBase = "https://github.com/vvasuki/mImAMsA/edit/master/content/"
  contactLink = "https://github.com/vvasuki/mImAMsA/issues/new"
  env = "production"
  disqusShortcode = "vvasuki-site"

[markup.goldmark.renderer]
  unsafe= true
